# Nivell 1

## Exercici 1

Crea una funció que donat un Array d’una dimensió, et faci un resum estadístic bàsic de les dades. Si detecta que l’array té més d’una dimensió, ha de mostrar un missatge d’error.

In [2]:
import numpy as np


In [4]:
test = np.arange(6)

def summary_array(x):
    if np.ndim(x)==1:
        print("La media es: ", np.mean(x))
        print("La desviación estándar es: ", np.std(x))
        print("Valor máximo: ", np.max(x))
        print("Valor mínimo: ", no.min(x))
        RIQ = np.quantile(x, 0.75) - np.quantile(x, 0.25)
        print("El rango intercuantilico es: ", RIQ)
        print("El bigote inferior es: ", np.quantile(x, 0.25)-(1.5*RIQ))
        print("El cuantil 25 es: ", np.quantile(x, 0.25))
        print("La mediana es: ", np.median(x))
        print("El cuantil 75 es: ", np.quantile(x, 0.75))        
        print("El bigote superior es: ", np.quantile(x, 0.75)+(1.5*RIQ))
    else:
        print("La matriz tiene que ser de una dimensión")
 

summary_array(test)

[0 1 2 3 4 5]
La media es:  2.5
La desviación estándar es:  1.707825127659933
El rango intercuantilico es:  2.5
El bigote inferior es:  -2.5
El cuantil 25 es:  1.25
La mediana es:  2.5
El cuantil 75 es:  3.75
El bigote superior es:  7.5


## Exercici 2

Crea una funció que et generi un quadrat NxN de nombres aleatoris entre el 0 i el 100.

In [6]:
def aleat():
    x = int(input("Introdueix un número per determinar el tamany de la matriu: "))
    arr = np.random.randint(100, size=(x,x))
    return arr

arr = aleat()
print(arr)

Introdueix un número per determinar el tamany de la matriu: 5
[[61 66  7 57 69]
 [49 84 36 22 94]
 [16 56 61 11 98]
 [50 78 17 65 28]
 [20 10 25  8 95]]


# Exercici 3

Crea una funció que donada una taula de dues dimensions, et calculi els totals per fila i els totals per columna. 

In [11]:
arr = aleat()
print(arr)

def totals(x):
    col = np.sum(x, axis = 0)
    row = np.sum(x, axis = 1)
    print("Columnes: {}\n files: {}".format(col, row))
    return col,row

totals(arr)

Introdueix un número per determinar el tamany de la matriu: 2
[[44 20]
 [37 46]]
Columnes: [81 66]
 files: [64 83]


(array([81, 66]), array([64, 83]))

## Exercici 4

Implementa manualment una funció que calculi el coeficient de correlació. Informa’t-en sobre els seus usos i interpretació.


El coeficient de correlació de Pearson, r, mostra la relació lineal que hi ha entre dues variables com pot ser l'alçada i el pes. Aquesta correlació pren valors entre 0 i 1, sent com més a prop de 1 millor correlació entre les dues variables. Mentre que si està més a prop de 0 vol dir que la relació entre les dues variables és molt feble. A més, si són valors negatius vol dir que són inversament proporcionals, mentre que si el valor és positiu vol dir que son directament proporcionals. Per obtenir aquesta correlació es fa a través del següent càlcul:

$r_{xy} = \frac{\sum_{i=1}^{n} (x_i - \bar{x}) (y_i - \bar{y})}{(n-1)S_x·S_y}$

Bibliografia: Shahbaba B. Biostatistics with R: An Introduction to Statistics Through Biological Data. 2012. Springer. pàg. 66 

In [3]:
'''
La funció treballarà amb una array de dos dimensions. On la primera fila
es una variable x i la segona fila és una altre variable y
'''

dades = np.random.randint(50, size=(2,8))
print(dades)
len(dades[0,:])-1

dades2 = np.array([[62,71,65,73,60],
                  [160,198,173,182,143]])

dades3 = np.array([[1,2,3,4],
                  [1,2,3,4]])

[[ 2 38 17 22 14 43 43  4]
 [18 44 43 33 22 29 45 34]]


In [7]:
def correlacio(matriu):
    x = matriu[0,:]
    y = matriu[1,:]
    n = len(x)-1
    x_mean = np.mean(x)
    y_mean = np.mean(y)
    sumP = 0
    
    for  con, (vx, vy) in enumerate(zip(x,y)):
        produc = (vx-x_mean)*(vy-y_mean)
        sumP = sumP + produc
        
    deno = n*np.std(x, ddof =1)*np.std(y, ddof = 1)
    
    corr = sumP/deno
            
    return corr
        
        
    

In [8]:
print(correlacio(dades3))

1.0
